# resolver: nightly-2023-01-31 # ghc-9.4.4
# resolver: lts-20.9 # ghc-9.2.5
resolver: lts-19.33 # ghc-9.0.2
# resolver: lts-18.28 # ghc-8.10.7
# resolver: lts-18.6 # ghc-8.10.4 # Currently the only version that seems to work with LiquidHaskell
packages:
  - .
allow-newer: true
extra-deps:
  # For LiquidHaskell:
  - text-format-0.3.2
  - Diff-0.3.4
  - optparse-applicative-0.16.1.0
  - rest-rewrite-0.3.0
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: b8780ee8d73d123adb39675ef87a2883f8aa1ecd
    subdirs:
      - .
      - liquid-base
      - liquid-vector
      - liquid-bytestring
      - liquid-containers
      - liquid-ghc-prim 
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 5aed39ec3210b9093ed635693d01bf351e25392f
