# This file is attempting to maintain the working Liquid Haskell versions
# that coorispond to a specific GHC or Stackage version

# resolver: nightly-2023-07-06  # ghc-9.6.2
resolver: lts-21.1 # ghc-9.4.5
# resolver: lts-20.26 # ghc-9.2.8
# resolver: lts-19.33 # ghc-9.0.2
# resolver: lts-18.28 # ghc-8.10.7
# resolver: lts-18.6 # ghc-8.10.4 # Error: [S-7441]
# resolver: lts-16.31 # ghc-8.8.4 # Fails To Build! ghc: panic! (the 'impossible' happened)
# resolver: lts-14.27 # ghc-8.6.5 # Fails To Build! ghc: panic! (the 'impossible' happened)
packages:
  - .
allow-newer: true
extra-deps:
  # For Test
  - Chart-1.9.4
  - Chart-cairo-1.9.3
  - cairo-0.13.10.0
  # For LiquidHaskell:
  # - hashable-1.3.5.0 # lts-20.16 and below
  - hashable-1.4.2.0 # ghc-9.4.4
  - text-format-0.3.2
  - Diff-0.3.4
  - optparse-applicative-0.16.1.0
  # - rest-rewrite-0.3.0 # ye olde reliable
  - rest-rewrite-0.4.1 # latest
  - smtlib-backends-0.3 # ghc-9.2.7
  - smtlib-backends-process-0.3 # ghc-9.2.7
  - git: https://github.com/ucsd-progsys/liquidhaskell 
    # commit: <something> # ghc-9.4.4 "Generically" errors out! Ambiguous occurrence ‘Generically’: It could refer to... ‘GHC.Generics.Generically’ or 'Language.Haskell.Liquid.Types.Generics.Generically'
    commit: 63337d432b47c1ba1ec9925db0994fc5cdce3eaf # ghc-9.2.7
    # commit: b8780ee8d73d123adb39675ef87a2883f8aa1ecd # ghc-9.0.2
    # commit: f917323a1f9db1677e592d6ffc81467d53588d70 # ghc-8.10.7
    subdirs:
      - .
      - liquid-base
      - liquid-vector
      - liquid-bytestring
      - liquid-containers
      - liquid-ghc-prim 
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 0e1a4725793740f495c26957044c56488d6e1efc # ghc-9.2.7
    # commit: 5aed39ec3210b9093ed635693d01bf351e25392f # ghc-9.0.2
    # commit: 544f8b0ba6d03b060701961250cce012412039c4 # ghc-8.10.7
